package org.webtree.Base.DAO;

import org.webtree.Base.MVC.BaseModel;
import org.webtree.Base.MVC.BaseModelList;
import org.webtree.Node.Model.NodeModel;
import org.webtree.System.Exception.LoggedError;
import org.webtree.System.Exception.WebTreeException;
import org.webtree.System.WtDb;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;

/**
 * @author lucifer
 *         Date: 28.04.12
 *         Time: 20:21
 */
public class SqlDAO {

	protected final String SQLSTATE_DUPLICATE = "23505";

	protected static HashMap<String, PreparedStatement> statementsMap = new HashMap<String, PreparedStatement>();

	public SqlDAO() {
	}

	protected static Connection getConnect() {
		return WtDb.getConnect();
	}

	protected static PreparedStatement getStatement(String statement, int autoGeneratedKeys) throws SQLException {
		if (!statementsMap.containsKey(statement)) {
			statementsMap.put(statement, getConnect().prepareStatement(statement, autoGeneratedKeys));
		}
		return statementsMap.get(statement);
	}

	protected static PreparedStatement getStatement(String statement) throws SQLException {
		if (!statementsMap.containsKey(statement)) {
			statementsMap.put(statement, getConnect().prepareStatement(statement));
		}
		return statementsMap.get(statement);
	}

	protected String buildUpdateSet(HashMap<String, Object> values) throws SQLException {
		if (values.isEmpty()) {
			throw new SQLException("Empty values given");
		}
		String result = "";
		boolean first = true;
		String statementTemplate = "\"%s\" = ?";
		for (String key : values.keySet()) {
			if (first) {
				first = false;
			} else {
				result += ", ";
			}

			String sql = String.format(statementTemplate, key);
			PreparedStatement statement = getConnect().prepareStatement(sql);

			statement.setString(1, values.get(key).toString());

			System.out.println(statement);

			result += statement.toString();
		}
		return result;
	}

	protected void fillModelList(BaseModelList list, PreparedStatement statement) throws SqlDAOException {
		try {
			ResultSet result = statement.executeQuery();
			while (result.next()) {
				list.add(buildModel(result));
			}
		} catch (SQLException e) {
			throw new SqlDAOException(e);
		}
	}

	//TODO: abstract
	protected BaseModel buildModel(ResultSet resultSet) throws SqlDAOException {
		try {
			NodeModel nodeModel = new NodeModel();
			nodeModel.setId(Integer.parseInt(resultSet.getString("nodeId")));
			nodeModel.setOwnerId(resultSet.getInt("ownerId"));
			try {
				nodeModel.setTitle(resultSet.getString("title"));
			} catch (NodeModel.NodeModelError nodeModelError) {
				throw new LoggedError(nodeModelError);
			}
			nodeModel.setRate(resultSet.getInt("rate"));
			try {
				nodeModel.setTitle(resultSet.getString("title"));
			} catch (NodeModel.NodeModelError nodeModelError) {
				throw new LoggedError(nodeModelError);
			}
			return nodeModel;
		} catch (SQLException e) {
			throw new SqlDAOException(e);
		}
	}


	protected int getOffset(int page, int limit) {
		return (page - 1) * limit;
	}

	public static class SqlDAOException extends WebTreeException {
		public SqlDAOException(SQLException e) {
			super(e);
		}

		public SqlDAOException() {
			super();
		}
	}
}
